### ISSUE TITLE
[!] The platform of the target `XYZ` (iOS 7.0) is not compatible with `FTMoreApps (0.1.1)` which has a minimum requirement of iOS 8.0.

### ISSUE THREAD

**Issue by buidinhduong** [ftapps/FTMoreApps#1]

**Comment by buidinhduong** [comment]
[!] The platform of the target `XYZ` (iOS 7.0) is not compatible with `FTMoreApps (0.1.1)` which has a minimum requirement of iOS 8.0.

This should support from ios 7+

**Comment by ftapps** [comment]
Updated to version 0.1.2 with support for iOS 7.
