### ISSUE TITLE
[Crash] When content loading in view FTMoreApps and tap Done to dismiss

### ISSUE THREAD

**Issue by chuongtrh** [ftapps/FTMoreApps#3]
Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x0000000197cb00b4 objc_retain + 20
1  Curious                        0x000000010010855c **49-[FTMoreAppsCell setPortraitScreenshot:position:]_block_invoke (FTMoreAppsCell.m:844)
2  libdispatch.dylib              0x0000000198315994 _dispatch_call_block_and_release + 24
3  libdispatch.dylib              0x0000000198315954 _dispatch_client_callout + 16
4  libdispatch.dylib              0x000000019831a20c _dispatch_main_queue_callback_4CF + 1608
5  CoreFoundation                 0x0000000185f7b544 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE** + 12
6  CoreFoundation                 0x0000000185f795ec __CFRunLoopRun + 1492
7  CoreFoundation                 0x0000000185ea4f74 CFRunLoopRunSpecific + 396
8  GraphicsServices               0x000000018f8ff6fc GSEventRunModal + 168
9  UIKit                          0x000000018aaa6d94 UIApplicationMain + 1488
10 Curious                        0x0000000100133a10 main (main.m:14)
11 libdyld.dylib                  0x0000000198342a08 start + 4

Fix it:
Change
-@property (assign, nonatomic) id <FTMoreAppsCellDelegate> delegate;

To
+@property (weak, nonatomic) id <FTMoreAppsCellDelegate> delegate;

**Comment by ftapps** [comment]
Fixed. Thank you!
