### ISSUE TITLE
SKStoreProductViewController parameters switched

### ISSUE THREAD

**Issue by vandenbrakel** [ftapps/FTMoreApps#4]
Hi there.

If you want to earn some affiliate income you should correct this:

[parametersDict setObject:SKStoreProductParameterAffiliateToken forKey:@"10lwC5"];
to:
[parametersDict setObject:@"10lwC5" forKey:SKStoreProductParameterAffiliateToken]; 

And it should be configurable IMO.

Same for SKStoreProductParameterCampaignToken.

Cheers.

**Comment by ftapps** [comment]
Thank you for pointing that. Fixed now. I will also change to be configurable in future releases.
