### ISSUE TITLE
Doesn't show app icons..

### ISSUE THREAD

**Issue by umekun123** [ftapps/FTMoreApps#5]
Thanks for the nice one, but Is this the issue for the library or Apple side, I am not sure.
The app icons part are all blank when I open it.

**Comment by ftapps** [comment]
This is due to the iOS 9 security that block access to non secure URLs. You need to open your Info.plist file and add the NSAppTransportSecurity dictionary, and then create the NSAllowsArbitraryLoads item within that, with a boolean type set to YES.
